server:
  # config app port
  port: 8080
  # config to dinh vi microservice
  servlet:
    context-path: /identity

spring:
  # config database connection
  datasource:
    url: "jdbc:mysql://localhost:3307/identity_service"
    username: root
    password: 123456
  # config jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

